### ISSUE TITLE
Implement a Main Menu

### ISSUE THREAD

**Issue by adonutwithsprinklez** [adonutwithsprinklez/CodeNameEmpty#31]
The game should contain a main menu from which the player can choose to start a new game, change settings, view data packs, and exit the game.

- [x] (Issue #12) Boot to Main Menu
- [x] Start a new game
- [x] (Issue #32) Change Settings
- [x] (Issue #33) Change Data Packs
- [x] (Issue #9) Exit Game

**Comment by adonutwithsprinklez** [comment]
Finally added data pack screen in latest nightly. Will push to master with next major update.
