### ISSUE TITLE
GUI Rework

### ISSUE THREAD

**Issue by adonutwithsprinklez** [adonutwithsprinklez/CodeNameEmpty#71]
Currently the project uses the console/terminal to display all output. This is sufficient for development of core features, but a real user interface is needed to allow accessibility to as many people as possible.

A rework of the user interface will require a lot of work, but luckily most of it will not be rewrites. Most of the changes/additions will be brand new features. The initial steps that must be taken to making this change will be 
ensuring that all current features continue working and that the ability to compile the source to a windows application is not lost. After that is accomplished, any extra features to the user interface can start being implemented.

This issue will not address any possible new features that are possible to the new user interface. Those will be addressed within a separate issue.

Re-implement current features:
- [x] (Issue #72) Ensure application compilation is still possible
- [x] (Issue #73) Functionality to display text is still available
- [x] (Issue #74) Functionality to accept user input
- [x] (Issue #75) Functionality to process input and update the display
- [x] Proper application startup and shutdown is still in tact

**Comment by adonutwithsprinklez** [comment]
Current Nightly build fulfils all requirements
